// Generated by CoffeeScript 1.6.3
(function() {
  var exports;

  exports = {
    create: function(alarm) {
      return {
        id: '12345',
        user: 'will',
        description: 'wake up',
        repeat: true,
        frequency: 'daily',
        alarmTime: '2014-03-18T18:53:27.782Z',
        goBack: 30,
        goBackScale: 'minutes'
      };
    },
    "delete": function(alarm) {}
  };

}).call(this);
