// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    firstName: "Charlie",
    lastName: "Harrison",
    email: "charliewharrison@gmail.com",
    emailAlternate: "charlesharrison@forrestbirdcharterschool.org",
    phone: "208-255-5304",
    address: "4310 Burns Ct.",
    city: "Sandpoint",
    state: "ID",
    zip: "83864"
  };

}).call(this);
