// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(socket) {
    var countdown, user;
    countdown = require('../public/scripts/wholeHouse.js');
    user = require('./userService.js');
    return {
      socket: socket,
      user: user,
      countdownValue: countdown.randrange(7, 15),
      emitTo: 'countdown',
      delay: 1000,
      name: '<user>',
      endmessage: "Time's Up!",
      greeting: {
        formal: 'How do you do?',
        casual: 'hi',
        regular: 'hello',
        computer: 'greetings'
      }
    };
  };

}).call(this);
