// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(socket) {
    return socket.on('sendChat', function(data) {
      return socket.emit('updateChat', socket.username, data);
    });
  };

}).call(this);
