// Generated by CoffeeScript 1.6.3
(function() {
  var Step, wH, _;

  _ = require('underscore');

  wH = require('./wholeHouse.coffee');

  Step = require('./step.coffee');

  exports["delete"] = function(options) {
    var settings;
    return settings = {
      todo: console.log("todo")
    };
  };

  exports.create = function(options) {
    var checklist, settings;
    settings = {
      description: "New Checklist " + (wH.randrange(1000, 9999)),
      steps: [],
      sortOrder: null,
      required: false
    };
    _.extend(settings, options);
    checklist = {
      addStep: function() {
        var step;
        step = Step();
        return settings.steps.push(step);
      },
      removeStep: function(stepID) {
        return {
          todo: console.log("who: authorized user\nwhat: remove step\nwhen: any time\nwhere: anywhere\nhow: fill in here\nwhy: remove item event")
        };
      },
      orderSteps: function() {
        return {
          todo: console.log("who: authorized user\nwhat: change order\nwhen: any time\nwhere: anywhere\nhow: fill in here\nwhy: reorder event")
        };
      }
    };
    return checklist;
  };

}).call(this);
