// Generated by CoffeeScript 1.6.3
(function() {
  var wH, _;

  _ = require('underscore');

  wH = require('./wholeHouse.coffee');

  exports.create = function(options) {
    var complete, description, step;
    ({
      description: "New list item " + (wH.randrange(1000, 9999))
    });
    _.extend(settings, options);
    description = settings.description;
    complete = false;
    step = {
      getStep: {
        todo: console.log("who: authorized user\nwhat: search for step, add if found, alert if not\nwhen: anytime\nwhere: anywhere\nhow:\n  search\n  if found\n    present found steps\n    allow to add to list\n  else\n    alert none found\nwhy: add steps to list"),
        newStep: {
          todo: console.log("who: authorized user\nwhat: search for similar steps, present if found, add step if not found\nwhen: anytime\nwhere: anywhere\nhow:\n  search for simliar steps\n  if found\n    present to user\n    if user selects existing step\n      add step to list\n  else\n    allow user to create new step\nwhy: create list item event")
        }
      }
    };
    return step;
  };

}).call(this);
