// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(data) {
    module.db = orient;
    return module.db.createVertex(data.user, {
      'class': 'User'
    }, function(err) {
      if (err) {
        return next(err);
      }
    });
  };

}).call(this);
