// Generated by CoffeeScript 1.6.3
(function() {
  var io, wH;

  io = require('./sockets.js');

  wH = {};

  exports.countdown = function(milliseconds, update, complete) {
    var callback, frequency, start;
    if (complete == null) {
      complete = null;
    }
    start = new Date;
    frequency = 100;
    callback = function() {
      var now, timeLeft;
      now = new Date;
      timeLeft = new Date((milliseconds + 1000) - (now - start));
      update(timeLeft);
      if (now - start < milliseconds) {
        return setTimeout(callback, frequency);
      } else if (complete) {
        return complete();
      }
    };
    return setTimeout(callback, frequency);
  };

  exports.padLeft = function(length, string, padString) {
    var i, _i, _ref;
    string = string.toString();
    if (string.length < length) {
      for (i = _i = 1, _ref = length - string.length; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
        string = padString + string;
      }
    }
    return string;
  };

  exports.randrange = function(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  };

  exports.countdownEmit = function(data) {
    var callback, _ref, _ref1;
    data.socket.emit(data.emitTo, {
      display: "" + ((_ref = data.greeting.regular) != null ? _ref : null) + " " + ((_ref1 = data.name) != null ? _ref1 : null)
    });
    callback = function() {
      var _ref2;
      if (data.countdownValue >= 0) {
        data.socket.emit(data.emitTo, {
          display: data.countdownValue
        });
        data.countdownValue--;
        return setTimeout(callback, 1000);
      } else {
        return data.socket.emit(data.emitTo, {
          display: (_ref2 = data.endMessage) != null ? _ref2 : null
        });
      }
    };
    return setTimeout(callback, 1000);
  };

  exports.wH.user = [
    {
      id: '',
      userName: 'Will',
      uri: {
        nexus10: 'wh:24.75.121.111.will.nexus10',
        iphone: 'wh:24.75.121.111.will.iphone',
        desktop: 'wh:24.75.121.111.will.desktop'
      },
      name: 'Will Harrison',
      preferences: {
        notifications: {
          alarm: {
            uri: {
              primary: this.iphone,
              secondary: this.desktop
            }
          },
          event: {
            uri: {
              primary: this.desktop,
              secondary: this.iphone,
              tertiary: this.nexus10
            }
          }
        }
      }
    }, {
      id: '',
      userName: 'Kristi',
      uri: {
        iphone: 'wh:24.75.121.111.kristi.iphone',
        netbook: 'wh:24.75.121.111.kristi.netbook',
        desktop: 'wh:24.75.121.111.kristi.desktop'
      }
    }
  ];

}).call(this);
