// Generated by CoffeeScript 1.6.3
(function() {
  var parser;

  parser = require('./../public/scripts/parser.coffee');

  exports.action = Model({
    id: [string, auto],
    description: [string, required],
    command: [[string, required]],
    parser: [parser]
  });

}).call(this);
