// Generated by CoffeeScript 1.6.3
(function() {
  var alarm, getAlarm;

  alarm = require('./alarm.coffee');

  exports.goTime = Model({
    id: [string, auto],
    description: [string, required],
    goTime: [Date, required],
    useAlarm: [bool, required],
    alarm: [alarm, optional]
  });

  getAlarm = function(useAlarm, alarm) {
    var a;
    this.useAlarm = useAlarm;
    if (this.alarm) {
      a = alarm();
      return alarm = a.create(options);
    }
  };

}).call(this);
