// Generated by CoffeeScript 1.6.3
(function() {
  var getDistance, getMap;

  exports.location = Model({
    id: [string, auto],
    description: [string, required],
    coordinates: [optional]
  }, {
    lat: [string, optional],
    long: [string, optional],
    map: [uri, optional],
    distance: [float, optional]
  });

  getMap = function(coordinates) {
    this.coordinates = coordinates;
    if (this.map) {

    }
  };

  getDistance = function(coordinates) {
    this.coordinates = coordinates;
    if (this.distance) {

    }
  };

}).call(this);
