// Generated by CoffeeScript 1.6.3
(function() {
  exports.user = Model({
    id: [string, auto],
    userName: [string, required],
    uri: [
      string, {
        devices: [string, attributes]
      }
    ],
    name: [string, required],
    preferences: [
      [
        {
          prefId: [string],
          prefSetting: [string]
        }
      ]
    ]
  });

}).call(this);
