// Generated by CoffeeScript 1.6.3
(function() {
  var action, goTime, location, process, reason, user;

  user = require('./user.coffee');

  action = require('./action.coffee');

  goTime = require('./goTime.coffee');

  location = require('./location.coffee');

  process = require('./process.coffee');

  reason = require('./reason.coffee');

  exports.wholeHouse = Model({
    user: user,
    process: process,
    goTime: goTime,
    location: location,
    process: process,
    reason: reason
  });

}).call(this);
